### ISSUE TITLE
GLSL to HLSL issues

### ISSUE THREAD

**Issue by sihsih** [smkplus/ShaderMan#12]
I am trying to convert GLSL from shadertoy to unity HLSL shaderlab. And I have below error messages:

- error in 'ShaderMan/matrix3D': incorrect number of arguments to numeric-type constructor at line 81 (on d3d11)

- invalid subscript "y" at line 124

Please help what is wrong with my code. Thanks. The original code from shadertoy(GLSL): https://www.shadertoy.com/view/4t3BWl

The converted code from unity shaderlab:
https://answers.unity.com/questions/1572270/glsl-to-hlsl.html

please help.
Thank you so much!

**Comment by smkplus** [comment]
I tried to convert this shader but It's hard to convert and have many errors
this shader have many calculation and even you convert it isn't good for using in game engine.
you can make optimal version of this effect inside unity if you want.
Just use trail Renderer

@sihsih

**Comment by sihsih** [comment]
Noted with many thanks.
Thanks for replying.
