### ISSUE TITLE
Web tool performance problems

### ISSUE THREAD

**Issue by Moarkill** [smkplus/ShaderMan#19]
The webpage for the web tool is causing my entire computer to slow down. This seems to be very dependant on resolution, perhaps rendering at a fraction of the screen would be ideal?

I'm running:
macOS 10.14.6
Safari 13.0.4

I'm attaching a H.264 recording of the problem. Please note that the performance of the website did not seem to be affected by the screen recording.

[Web Tool.zip](https://github.com/smkplus/ShaderMan/files/4380046/Web.Tool.zip)

**Comment by smkplus** [comment]
Hi ok I will remove the background shader

**Comment by smkplus** [comment]
yes it's complicated and confused me
this is the chapter 13 of the book of shaders
as you can see there is part to write glsl math and it will run in 2d
coordinate
I used this tool to draw above triangles
https://thebookofshaders.com/13/

**Comment by smkplus** [comment]
so if you know desmos can you take me a simple code that works in desmos?

**Comment by smkplus** [comment]
https://github.com/smkplus/ShaderMan.io
I fixed this issue
