### ISSUE TITLE
No workee in Unity 2020.1.10f1

### ISSUE THREAD

**Issue by giantkiller** [smkplus/ShaderMan#26]
I see a lot of pink shader posts here.
Does anybody think the developer will correct?

**Comment by smkplus** [comment]
@giantkiller Hello unfortunately this plugin no longer supported
If you want to convert the shader please let me know
 I can help you

**Comment by giantkiller** [comment]
Thank you. I could use help. My initial concern is that the GLSL variants have strayed far from what they were when you wrote this or HLSL has changed significantly also.
The https://www.shadertoy.com/view/WtSfWK
//-----------------------------------------------
// main = animate + render + color grade
//-----------------------------------------------
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
	// init random seed
    ivec2 q = ivec2(fragCoord);

and then the converter shows:
fixed4 frag(VertexOutput i) : SV_Target
	{

		// init random seed
		fixed2 q = fixed2(i.uv, i.uv);
The compiler errors at this line fixed2(i.uv, i.uv); with incorrect number of arguments to numeric-type constructor
So I am not sure about line of code. My hunch is the converter got confused.
I know C. I am weak on writing structs but I understand them when I see them.
And I could not find an explanation of fixed2(i.uv, i.uv) with or why 2 parameters.
I see a lot of of ShaderToy shaders and I want to get to the point of grabbing them, running them through your converter then repairing them of the nuances. With a big 'if that is possible?'
Thank you for your previous response.

**Comment by giantkiller** [comment]
Thank you. I could use help. My initial concern is that the GLSL variants have strayed far from what they were when you wrote this or HLSL has changed significantly also.
The https://www.shadertoy.com/view/WtSfWK
//-----------------------------------------------
// main = animate + render + color grade
//-----------------------------------------------
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
	// init random seed
    ivec2 q = ivec2(fragCoord);

and then the converter shows:
fixed4 frag(VertexOutput i) : SV_Target
	{

		// init random seed
		fixed2 q = fixed2(i.uv, i.uv);
The compiler errors at this line fixed2(i.uv, i.uv); with incorrect number of arguments to numeric-type constructor
So I am not sure about line of code. My hunch is the converter got confused.
I know C. I am weak on writing structs but I understand them when I see them.
And I could not find an explanation of fixed2(i.uv, i.uv) with or why 2 parameters.
I see a lot of of ShaderToy shaders and I want to get to the point of grabbing them, running them through your converter then repairing them of the nuances. With a big 'if that is possible?'
Thank you for your previous response.
