### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by andybak** [smkplus/ShaderMan#3]
There's something in the readme but I'm not a lawyer. It sounds like an attempt to apply CC-NC to code which would make this project difficult for anyone else to contribute to or use in other open source projects. Was this your intention?

 It would be best to choose an existing well understood source code licence. If you do want it to be open source then a non-commercial clause might be problemmatic: https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project

**Comment by smkplus** [comment]
oh sorry that was my old readme (before i decide to open source) i should delete 
it's free and open source.

**Comment by iBicha** [comment]
@smkplus  I was wondering about this as well, should probably add a `LICENSE` file to the repo (maybe MIT?)
