### ISSUE TITLE
[API] Convert from link

### ISSUE THREAD

**Issue by iBicha** [smkplus/ShaderMan#7]
I was about to start such project, when I stumbled on this. Pretty good work!

A fun enhancement can be working with https://www.shadertoy.com/api

So from a link, one can regex the shader id, download meta data, and then download code, textures and such, convert the shader, and create a material and assigning the downloaded texture! 

Next step can be downloading the audio and assigning it to an audio source.

These are my thoughts, I can help with this

**Comment by smkplus** [comment]
It's good idea thanks....!
If you help me I'll happy because :D
I need your help

**Comment by smkplus** [comment]
> So from a link, one can regex the shader id, download meta data, and then download code, textures and such, convert the shader, and create a material and assigning the downloaded texture!

It's good idea thanks....!
If you help me I'll happy because :D
I need your help

**Comment by iBicha** [comment]
I got jammed with work, might not be able to contribute to this in the near future.

**Comment by iBicha** [comment]
I will be closing this as I won't be finding time for it.
Please reopen if needed
